version: '3'

services:
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - 2717:27017
    environment:
      TZ: Europe/Istanbul
  
  calendar_app:
    build: .
    ports:
      - 3000:3000
    environment:
      PORT: 3000
      MONGODB_URI: mongodb://mongo_db:27017
      DB_NAME: calendar
    depends_on:
      - mongo_db

volumes:
  mongo_db: {}